### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by manoranjan-singh** [kpramesh2212/openapi-merger-plugin#15]
Dear K P Ramesh, We are using this gradle plugin to merge open API specifications. We have found issue related to order of files which is fixed by [this](https://github.com/kpramesh2212/openapi-merger-plugin/pull/11) PR. Can you please **release** the latest code. So, that we will able to leverage the good work which you have done. Thank You.

**Comment by kpramesh2212** [comment]
@manoranjan-singh 

After a long time I have started working on it again so might take a week or 2 before i can do a release

But sure will do another release as soon as possible

**Comment by manoranjan-singh** [comment]
@kpramesh2212 Thank you. Looking forward for a new release...

**Comment by kpramesh2212** [comment]
1.0.5 released
