### ISSUE TITLE
Support for subfolder files?

### ISSUE THREAD

**Issue by asyba** [kpramesh2212/openapi-merger-plugin#4]
For example I have openApi.json and sub folder 
```
"parameters" : [ {
          "$ref" : "../common/components/headers/contentType.json"
        }
```

I would like to have all files related to the openAPI.json in a big file.

**Comment by kpramesh2212** [comment]
@asyba 

I couldn't understand what your trying to achieve.

Can you please provide little bit in-depth explanation for what your trying to achieve.

**Comment by asyba** [comment]
> @asyba
> 
> I couldn't understand the problem your tying to solve.
> 
> Can you please provide little bit in-depth explanation for what your trying to achieve.

I have java project with openAPI.json files but some specifications are not in the root file, there are in sub-folder.
For example a response.json is used across different openAPI.json files so I created one common file and use $ref.

`"parameters" : [ {
: {
          "200" : {
            "$ref" : "../common/components/responses/xxxxx.json"
          },`
          
To be able to import the openAPI.json in to Postman for example, doesn't work if the openAPI.json does't contain all the data.
I need to able to have it all in one file.

Example of another github project https://github.com/APIDevTools/swagger-cli#combine-multiple-files
but they don't provide a gradle plugin task that I need in my case.

**Comment by kpramesh2212** [comment]
@asyba 

ok understood the problem now.

What I think is 

Its possible to combine multiple files into one file.

However after combining all files the following would become invalid

 "$ref" : "../common/components/responses/xxxxx.json" 

since file xxxxx.json which was in that path (../common/components/responses/) is now part of the merged file openapi.json.

**Comment by kpramesh2212** [comment]
@asyba 

I think this feature can be cleanly implemented. 

Will work on this one and add it to the next release.

**Comment by cemo** [comment]
Is this feature implemented @kpramesh2212. 
Thanks for the plugin.

**Comment by kpramesh2212** [comment]
Will test and do a release as soon as possible

**Comment by kpramesh2212** [comment]
1.0.5 released
