### ISSUE TITLE
Configuring <<servers>> object 

### ISSUE THREAD

**Issue by muradhajiyev** [kpramesh2212/openapi-merger-plugin#6]
Thanks for this plugin.

I'm looking for an opportunity to configure servers objects. I don't want to include sub servers in the merged file. It would be nice If I can configure whatever server I want.

**Comment by kpramesh2212** [comment]
@muradhajiyev 

Is this issue same as #5

**Comment by kpramesh2212** [comment]
If its not the same issue.

Could you please elaborate your request with a sample file.

A sample example files showing

The unmerged files and final merged files.

**Comment by muradhajiyev** [comment]
@kpramesh2212 That's exactly the same problem I was trying to explain. I didn't check the previous issue before opening this one. Thanks

**Comment by kpramesh2212** [comment]
Hi 

This feature should be avilable in the newer version.

Can you please check and provide feedback?

Regards
Ramesh

**Comment by muradhajiyev** [comment]
@kpramesh2212 Sure, I'll definitely put my feedback here.
Thank you :)

**Comment by muradhajiyev** [comment]
@kpramesh2212 I had a chance to test it. It works as expected. Thank you!
